version: "3"

volumes:
  postgres_volume:

networks:
  internal:

services:
  event-organizer:
    build: ./
    environment:
      - TZ=Europe/Kiev
      - POSTGRES_DB_ADDR=db
      - POSTGRES_DB_PORT=5432
      - DB_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=thisisnewsecurepassword
      - PG_DATABASE=gino
      - DB_PORT=5432
      - DB_USER=vihovin
      - DB_PASSWORD=thisissomenewpass
    depends_on:
      - "db"
    links:
      - "db"
    ports:
      - 0.0.0.0:8000:8000

  db:
    image: library/postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=thisisnewsecurepassword
